services:
  # Backend API - zoptymalizowany
  - type: web
    name: portal-backend
    env: node
    plan: free
    buildCommand: cd backend && npm ci --only=production --prefer-offline
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://portal-frontend.onrender.com

  # Frontend React App - zoptymalizowany
  - type: web
    name: portal-frontend
    env: static
    buildCommand: cd frontend && npm ci --prefer-offline && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://portal-backend.onrender.com
      - key: REACT_APP_GOOGLE_MAPS_API_KEY
        value: AIzaSyB41DRUbKWJHPxaFjMAwdrzWzbVKartNGg 